services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cocktaildb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=cocktail'
    ports:
      - '5433:5432'
